import type { Event, Comment, User, Registration } from "./types"

export const mockUser: User = {
  id: "user-1",
  name: "Helena Silva",
  avatar: "/diverse-woman-avatar.png",
  isAdmin: false,
}

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Workshop de Desenvolvimento Web com React",
    description: "Aprenda os fundamentos do React e crie sua primeira aplicação web moderna.",
    longDescription:
      "Neste workshop intensivo de 4 horas, você aprenderá os conceitos fundamentais do React, incluindo componentes, hooks, estado e props. Construiremos juntos uma aplicação completa do zero, aplicando as melhores práticas da indústria. Ideal para desenvolvedores com conhecimentos básicos de JavaScript que querem dar o salto para o React.",
    date: "2025-11-15",
    time: "10:00 - 14:00",
    location: "Centro de Inovação Tech Hub, Sala 3A",
    organizer: "Tech Community São Paulo",
    category: "taller",
    coverImage: "/coding-workshop-modern.jpg",
    gallery: [
      "/react-code-screen.jpg",
      "/developers-working-together.jpg",
      "/laptop-programming.jpg",
      "/tech-workspace.jpg",
    ],
    attendees: 24,
    maxAttendees: 30,
  },
  {
    id: "2",
    title: "Conferência: O Futuro da IA",
    description: "Especialistas internacionais discutem as últimas tendências em inteligência artificial.",
    longDescription:
      "Junte-se a nós para uma conferência magistral onde líderes da indústria compartilharão suas visões sobre o futuro da inteligência artificial. Exploraremos temas como machine learning, ética em IA e as aplicações práticas que estão transformando indústrias. Inclui sessão de perguntas e respostas com os palestrantes.",
    date: "2025-11-20",
    time: "16:00 - 19:00",
    location: "Auditório Nacional de Convenções",
    organizer: "AI Summit Brasil",
    category: "conferencia",
    coverImage: "/ai-conference-futuristic.jpg",
    gallery: ["/conference-speaker-stage.jpg", "/audience-conference-hall.jpg", "/ai-technology-visualization.png"],
    attendees: 156,
    maxAttendees: 200,
  },
  {
    id: "3",
    title: "Networking: Startups & Investidores",
    description: "Conecte-se com empreendedores e investidores em um ambiente descontraído.",
    longDescription:
      "Uma noite projetada para facilitar conexões significativas entre startups em busca de financiamento e investidores interessados em projetos inovadores. O evento inclui apresentações rápidas de 3 minutos, networking livre com bebidas e aperitivos, e a oportunidade de estabelecer relacionamentos duradouros no ecossistema empreendedor.",
    date: "2025-10-28",
    time: "18:30 - 21:30",
    location: "Rooftop Bar Innovation Tower",
    organizer: "Startup Network Rio",
    category: "networking",
    coverImage: "/business-networking-rooftop.jpg",
    gallery: ["/business-networking.png", "/cocktail-event-professional.jpg", "/startup-pitch.png"],
    attendees: 45,
    maxAttendees: 50,
  },
  {
    id: "4",
    title: "Festival de Música Eletrônica",
    description: "Uma noite de música eletrônica com os melhores DJs locais.",
    longDescription:
      "Prepare-se para uma experiência musical inesquecível com uma lineup espetacular de DJs locais e internacionais. O festival contará com três palcos, instalações de arte interativa, food trucks gourmet e uma produção audiovisual de primeiro nível. Um evento imperdível para os amantes da música eletrônica.",
    date: "2025-11-25",
    time: "20:00 - 04:00",
    location: "Recinto de Feiras da Cidade",
    organizer: "Electronic Vibes",
    category: "cultural",
    coverImage: "/electronic-music-festival-lights.jpg",
    gallery: [
      "/dj-performing-crowd.jpg",
      "/concert-lights-audience.jpg",
      "/festival-stage-night.jpg",
      "/people-dancing-club.jpg",
    ],
    attendees: 892,
    maxAttendees: 1000,
  },
  {
    id: "5",
    title: "Exposição de Arte Contemporânea",
    description: "Descubra as obras de artistas emergentes em nossa galeria.",
    longDescription:
      "Uma exposição coletiva que reúne o trabalho de 15 artistas emergentes que estão redefinindo a arte contemporânea. A mostra inclui pinturas, esculturas, instalações multimídia e arte digital. Haverá um tour guiado pelo curador e a oportunidade de conhecer os artistas pessoalmente.",
    date: "2025-10-25",
    time: "11:00 - 20:00",
    location: "Galeria de Arte Moderna",
    organizer: "Coletivo Artístico Urbano",
    category: "cultural",
    coverImage: "/contemporary-art-gallery.png",
    gallery: [
      "/art-exhibition-paintings.jpg",
      "/modern-sculpture-gallery.jpg",
      "/placeholder.svg?height=300&width=400",
    ],
    attendees: 234,
    maxAttendees: 300,
  },
  {
    id: "6",
    title: "Workshop de Fotografia Urbana",
    description: "Aprenda técnicas de fotografia de rua com um fotógrafo profissional.",
    longDescription:
      "Um workshop prático onde você aprenderá as técnicas essenciais da fotografia urbana e de rua. Começaremos com uma sessão teórica sobre composição, luz e narrativa visual, seguida de uma saída fotográfica pelo centro histórico. Terminaremos com uma sessão de revisão e edição das melhores fotos do dia.",
    date: "2025-10-22",
    time: "09:00 - 13:00",
    location: "Praça Central (ponto de encontro)",
    organizer: "Escola de Fotografia Visual",
    category: "taller",
    coverImage: "/placeholder.svg?height=400&width=800",
    gallery: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    attendees: 12,
    maxAttendees: 15,
  },
  {
    id: "7",
    title: "Conferência de Design UX/UI",
    description: "As últimas tendências em design de experiência do usuário.",
    longDescription:
      "Uma conferência completa sobre as tendências atuais em design UX/UI, com palestrantes de empresas líderes em tecnologia. Cobriremos temas como design inclusivo, sistemas de design, prototipagem rápida e a integração de IA no processo de design. Inclui workshops práticos e networking.",
    date: "2025-11-10",
    time: "09:00 - 18:00",
    location: "Centro de Convenções Digital",
    organizer: "Design Thinking Community",
    category: "conferencia",
    coverImage: "/placeholder.svg?height=400&width=800",
    gallery: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    attendees: 87,
    maxAttendees: 120,
  },
  {
    id: "8",
    title: "Mercado de Produtores Locais",
    description: "Apoie os produtores locais e desfrute de produtos frescos e artesanais.",
    longDescription:
      "Um mercado semanal que reúne mais de 40 produtores locais oferecendo frutas, verduras, queijos, pães artesanais, mel, vinhos e produtos orgânicos. Além das compras, haverá demonstrações de culinária ao vivo, música ao vivo e atividades para crianças. Uma experiência perfeita para toda a família.",
    date: "2025-10-26",
    time: "08:00 - 14:00",
    location: "Parque Central",
    organizer: "Associação de Produtores Locais",
    category: "cultural",
    coverImage: "/placeholder.svg?height=400&width=800",
    gallery: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    attendees: 456,
    maxAttendees: 500,
  },
]

export const mockComments: Record<string, Comment[]> = {
  "1": [
    {
      id: "c1",
      eventId: "1",
      userId: "user-2",
      userName: "Carlos Oliveira",
      userAvatar: "/placeholder.svg?height=40&width=40",
      content:
        "Excelente workshop! Os instrutores foram muito claros e o conteúdo muito prático. Definitivamente recomendado para quem quer aprender React.",
      timestamp: "2025-10-15T14:30:00",
      isAdmin: false,
    },
    {
      id: "c2",
      eventId: "1",
      userId: "admin-1",
      userName: "Ana Martins",
      userAvatar: "/placeholder.svg?height=40&width=40",
      content:
        "Obrigada Carlos! Ficamos felizes que você tenha aproveitado o workshop. Em breve anunciaremos o nível avançado.",
      timestamp: "2025-10-15T15:00:00",
      isAdmin: true,
    },
    {
      id: "c3",
      eventId: "1",
      userId: "user-3",
      userName: "Laura Santos",
      userAvatar: "/placeholder.svg?height=40&width=40",
      content: "Adorei a parte prática. Haverá material adicional disponível?",
      timestamp: "2025-10-16T10:20:00",
      isAdmin: false,
    },
  ],
  "2": [
    {
      id: "c4",
      eventId: "2",
      userId: "user-4",
      userName: "David Lima",
      userAvatar: "/placeholder.svg?height=40&width=40",
      content:
        "Conferência fascinante. Os palestrantes realmente sabem do assunto e as previsões sobre IA foram muito interessantes.",
      timestamp: "2025-10-20T20:15:00",
      isAdmin: false,
    },
  ],
  "3": [
    {
      id: "c5",
      eventId: "3",
      userId: "user-5",
      userName: "Elena Torres",
      userAvatar: "/placeholder.svg?height=40&width=40",
      content: "Ótimo evento para fazer networking. Conheci vários investidores interessados no meu projeto.",
      timestamp: "2025-10-29T09:30:00",
      isAdmin: false,
    },
    {
      id: "c6",
      eventId: "3",
      userId: "user-6",
      userName: "Miguel Pereira",
      userAvatar: "/placeholder.svg?height=40&width=40",
      content: "Excelente organização e muito bom ambiente. Quando será o próximo?",
      timestamp: "2025-10-29T11:45:00",
      isAdmin: false,
    },
  ],
  "4": [],
  "5": [
    {
      id: "c7",
      eventId: "5",
      userId: "user-7",
      userName: "Isabel Fernandes",
      userAvatar: "/placeholder.svg?height=40&width=40",
      content: "As obras são impressionantes. Adorei a instalação multimídia do artista local.",
      timestamp: "2025-10-25T16:20:00",
      isAdmin: false,
    },
  ],
  "6": [],
  "7": [],
  "8": [],
}

export const mockRegistrations: Record<string, Registration[]> = {
  "1": [
    {
      id: "reg1",
      eventId: "1",
      fullName: "Carlos Oliveira",
      email: "carlos@email.com",
      phone: "+351 912 345 001",
      message: "Muito interessado em aprender React!",
      timestamp: "2025-10-10T14:30:00",
    },
    {
      id: "reg2",
      eventId: "1",
      fullName: "Laura Santos",
      email: "laura@email.com",
      phone: "+351 912 345 002",
      timestamp: "2025-10-11T09:15:00",
    },
    {
      id: "reg3",
      eventId: "1",
      fullName: "Pedro Costa",
      email: "pedro@email.com",
      phone: "+351 912 345 003",
      message: "Tenho alguma experiência com JavaScript",
      timestamp: "2025-10-12T16:45:00",
    },
  ],
  "2": [
    {
      id: "reg4",
      eventId: "2",
      fullName: "David Lima",
      email: "david@email.com",
      phone: "+351 912 345 004",
      timestamp: "2025-10-15T10:20:00",
    },
    {
      id: "reg5",
      eventId: "2",
      fullName: "Ana Rodrigues",
      email: "ana@email.com",
      phone: "+351 912 345 005",
      message: "Trabalho com IA e quero conhecer mais sobre as tendências",
      timestamp: "2025-10-16T14:30:00",
    },
  ],
  "3": [
    {
      id: "reg6",
      eventId: "3",
      fullName: "Elena Torres",
      email: "elena@email.com",
      phone: "+351 912 345 006",
      message: "Tenho uma startup de tecnologia educacional",
      timestamp: "2025-10-20T11:00:00",
    },
    {
      id: "reg7",
      eventId: "3",
      fullName: "Miguel Pereira",
      email: "miguel@email.com",
      phone: "+351 912 345 007",
      timestamp: "2025-10-21T15:30:00",
    },
  ],
  "4": [],
  "5": [
    {
      id: "reg8",
      eventId: "5",
      fullName: "Isabel Fernandes",
      email: "isabel@email.com",
      phone: "+351 912 345 008",
      message: "Sou artista e gostaria de expor no futuro",
      timestamp: "2025-10-18T13:20:00",
    },
  ],
  "6": [],
  "7": [],
  "8": [],
}
